---
# ==========
# NHL Config
# ==========
nhl:
    logoHref: "/public/img/nhl/nhl_shield.png"
    teams:
        # ==== WESTERN ====
        # Pacific
        -
            city: "Anaheim"
            mascot: "Ducks"
            conference: "Western"
            division: "Pacific"
            logoHref: "/public/img/nhl/teams/ducks_logo.svgz"
        - 
            city: "Calgary"
            mascot: "Flames"
            conference: "Western"
            division: "Pacific"
            logoHref: "/public/img/nhl/teams/flames_dark_logo.svgz"
        - 
            city: "Edmonton"
            mascot: "Oilers"
            conference: "Western"
            division: "Pacific"
            logoHref: "/public/img/nhl/teams/oilers_logo.svgz"
        - 
            city: "Los Angeles"
            mascot: "Kings"
            conference: "Western"
            division: "Pacific"
            logoHref: "/public/img/nhl/teams/kings_dark_logo.svgz"
        - 
            city: "Arizona"
            mascot: "Coyotes"
            conference: "Western"
            division: "Pacific"
            logoHref: "/public/img/nhl/teams/coyotes_logo.svgz"
        - 
            city: "San Jose"
            mascot: "Sharks"
            conference: "Western"
            division: "Pacific"
            logoHref: "/public/img/nhl/teams/sharks_logo.svgz"
        - 
            city: "Vancouver"
            mascot: "Canucks"
            conference: "Western"
            division: "Pacific"
            logoHref: "/public/img/nhl/teams/canucks_dark_logo.svgz"
        # Central
        - 
            city: "Chicago"
            mascot: "Blackhawks"
            conference: "Western"
            division: "Central"
            logoHref: "/public/img/nhl/teams/blackhawks_logo.svgz"
        - 
            city: "Colorado"
            mascot: "Avalanche"
            conference: "Western"
            division: "Central"
            logoHref: "/public/img/nhl/teams/avalanche_logo.svgz"
        - 
            city: "Dallas"
            mascot: "Stars"
            conference: "Western"
            division: "Central"
            logoHref: "/public/img/nhl/teams/stars_logo.svgz"
        - 
            city: "Minnesota"
            mascot: "Wild"
            conference: "Western"
            division: "Central"
            logoHref: "/public/img/nhl/teams/wild_logo.svgz"
        - 
            city: "Nashville"
            mascot: "Predators"
            conference: "Western"
            division: "Central"
            logoHref: "/public/img/nhl/teams/predators_logo.svgz"
        - 
            city: "St. Louis"
            mascot: "Blues"
            conference: "Western"
            division: "Central"
            logoHref: "/public/img/nhl/teams/blues_dark_logo.svgz"
        - 
            city: "Winnipeg"
            mascot: "Jets"
            conference: "Western"
            division: "Central"
            logoHref: "/public/img/nhl/teams/jets_logo.svgz"
        # ==== EASTERN ====
        # Atlantic
        - 
            city: "Boston"
            mascot: "Bruins"
            conference: "Eastern"
            division: "Atlantic"
            logoHref: "/public/img/nhl/teams/bruins_logo.svgz"
        - 
            city: "Buffalo"
            mascot: "Sabres"
            conference: "Eastern"
            division: "Atlantic"
            logoHref: "/public/img/nhl/teams/sabres_logo.svgz"
        - 
            city: "Detroit"
            mascot: "Red Wings"
            conference: "Eastern"
            division: "Atlantic"
            logoHref: "/public/img/nhl/teams/redwings_logo.svgz"
        - 
            city: "Florida"
            mascot: "Panthers"
            conference: "Eastern"
            division: "Atlantic"
            logoHref: "/public/img/nhl/teams/panthers_logo.svgz"
        - 
            city: "Montreal"
            mascot: "Canadiens"
            conference: "Eastern"
            division: "Atlantic"
            logoHref: "/public/img/nhl/teams/canadiens_logo.svgz"
        - 
            city: "Ottawa"
            mascot: "Senators"
            conference: "Eastern"
            division: "Atlantic"
            logoHref: "/public/img/nhl/teams/senators_logo.svgz"
        - 
            city: "Tampa Bay"
            mascot: "Lightning"
            conference: "Eastern"
            division: "Atlantic"
            logoHref: "/public/img/nhl/teams/lightning_dark_logo.svgz"
        - 
            city: "Toronto"
            mascot: "Maple Leafs"
            conference: "Eastern"
            division: "Atlantic"
            logoHref: "/public/img/nhl/teams/mapleleafs_dark_logo.svgz"
        # Metropolitan
        - 
            city: "Carolina"
            mascot: "Hurricanes"
            conference: "Eastern"
            division: "Metropolitan"
            logoHref: "/public/img/nhl/teams/hurricanes_logo.svgz"
        - 
            city: "Columbus"
            mascot: "Blue Jackets"
            conference: "Eastern"
            division: "Metropolitan"
            logoHref: "/public/img/nhl/teams/bluejackets_logo.svgz"
        - 
            city: "New Jersey"
            mascot: "Devils"
            conference: "Eastern"
            division: "Metropolitan"
            logoHref: "/public/img/nhl/teams/devils_logo.svgz"
        - 
            city: "New York"
            mascot: "Islanders"
            conference: "Eastern"
            division: "Metropolitan"
            logoHref: "/public/img/nhl/teams/islanders_logo.svgz"
        - 
            city: "New York"
            mascot: "Rangers"
            conference: "Eastern"
            division: "Metropolitan"
            logoHref: "/public/img/nhl/teams/rangers_logo.svgz"
        - 
            city: "Philadelphia"
            mascot: "Flyers"
            conference: "Eastern"
            division: "Metropolitan"
            logoHref: "/public/img/nhl/teams/flyers_dark_logo.svgz"
        - 
            city: "Pittsburgh"
            mascot: "Penguins"
            conference: "Eastern"
            division: "Metropolitan"
            logoHref: "/public/img/nhl/teams/penguins_logo.svgz"
        - 
            city: "Washington"
            mascot: "Capitals"
            conference: "Eastern"
            division: "Metropolitan"
            logoHref: "/public/img/nhl/teams/capitals_dark_logo.svgz"
# ==========
# NBA Config
# ==========
nba:
    logoHref: "/public/img/nba/nba-logo.png"
    teams:
        # ==== EASTERN ====
        # Atlantic
        -
            city: "Boston"
            mascot: "Celtics"
            conference: "Eastern"
            division: "Atlantic"
            logoHref: "/public/img/nba/teams/bos.gif"
        - 
            city: "Brooklyn"
            mascot: "Nets"
            conference: "Eastern"
            division: "Atlantic"
            logoHref: "/public/img/nba/teams/nets.gif"
        - 
            city: "New York"
            mascot: "Knicks"
            conference: "Eastern"
            division: "Atlantic"
            logoHref: "/public/img/nba/teams/nyk.gif"
        - 
            city: "Philadelphia"
            mascot: "76ers"
            conference: "Eastern"
            division: "Atlantic"
            logoHref: "/public/img/nba/teams/phi.gif"
        - 
            city: "Toronto"
            mascot: "Raptors"
            conference: "Eastern"
            division: "Atlantic"
            logoHref: "/public/img/nba/teams/raptors.gif"
        # Central
        -
            city: "Chicago"
            mascot: "Bulls"
            conference: "Eastern"
            division: "Central"
            logoHref: "/public/img/nba/teams/chi.gif"
        -
            city: "Cleveland"
            mascot: "Cavaliers"
            conference: "Eastern"
            division: "Central"
            logoHref: "/public/img/nba/teams/cavaliers.gif"
        -
            city: "Detroit"
            mascot: "Pistons"
            conference: "Eastern"
            division: "Central"
            logoHref: "/public/img/nba/teams/pistons_80X64.gif"
        -
            city: "Indiana"
            mascot: "Pacers"
            conference: "Eastern"
            division: "Central"
            logoHref: "/public/img/nba/teams/ind.gif"
        -
            city: "Milwaukee"
            mascot: "Bucks"
            conference: "Eastern"
            division: "Central"
            logoHref: "/public/img/nba/teams/bucks.gif"
        # Southeast
        -
            city: "Atlanta"
            mascot: "Hawks"
            conference: "Eastern"
            division: "Southeast"
            logoHref: "/public/img/nba/teams/hawks.gif"
        -
            city: "Charlotte"
            mascot: "Hornets"
            conference: "Eastern"
            division: "Southeast"
            logoHref: "/public/img/nba/teams/bobcats.gif"
        -
            city: "Miami"
            mascot: "Heat"
            conference: "Eastern"
            division: "Southeast"
            logoHref: "/public/img/nba/teams/heat.gif"
        -
            city: "Orlando"
            mascot: "Magic"
            conference: "Eastern"
            division: "Southeast"
            logoHref: "/public/img/nba/teams/magic.gif"
        -
            city: "Washington"
            mascot: "Wizards"
            conference: "Eastern"
            division: "Southeast"
            logoHref: "/public/img/nba/teams/wizards.gif"
        # ==== WESTERN ====
        # Southwest
        -
            city: "Dallas"
            mascot: "Mavericks"
            conference: "Western"
            division: "Southwest"
            logoHref: "/public/img/nba/teams/dal.gif"
        -
            city: "Houston"
            mascot: "Rockets"
            conference: "Western"
            division: "Southwest"
            logoHref: "/public/img/nba/teams/rockets.gif"
        -
            city: "Memphis"
            mascot: "Grizzlies"
            conference: "Western"
            division: "Southwest"
            logoHref: "/public/img/nba/teams/mem.gif"
        -
            city: "New Orleans"
            mascot: "Pelicans"
            conference: "Western"
            division: "Southwest"
            logoHref: "/public/img/nba/teams/pelicans.gif"
        -
            city: "San Antonio"
            mascot: "Spurs"
            conference: "Western"
            division: "Southwest"
            logoHref: "/public/img/nba/teams/spurs.gif"
        # Northwest
        -
            city: "Denver"
            mascot: "Nuggets"
            conference: "Western"
            division: "Northwest"
            logoHref: "/public/img/nba/teams/nuggets.gif"
        -
            city: "Minnesota"
            mascot: "Timberwolves"
            conference: "Western"
            division: "Northwest"
            logoHref: "/public/img/nba/teams/min.gif"
        -
            city: "Portland"
            mascot: "Trail Blazers"
            conference: "Western"
            division: "Northwest"
            logoHref: "/public/img/nba/teams/por.gif"
        -
            city: "Oklahoma City"
            mascot: "Thunder"
            conference: "Western"
            division: "Northwest"
            logoHref: "/public/img/nba/teams/okc.gif"
        -
            city: "Utah"
            mascot: "Jazz"
            conference: "Western"
            division: "Northwest"
            logoHref: "/public/img/nba/teams/uth.gif"
        # Pacific
        -
            city: "Golden State"
            mascot: "Warriors"
            conference: "Western"
            division: "Pacific"
            logoHref: "/public/img/nba/teams/warriors.gif"
        -
            city: "Los Angeles"
            mascot: "Clippers"
            conference: "Western"
            division: "Pacific"
            logoHref: "/public/img/nba/teams/clippers.gif"
        -
            city: "Los Angeles"
            mascot: "Lakers"
            conference: "Western"
            division: "Pacific"
            logoHref: "/public/img/nba/teams/lakers.gif"
        -
            city: "Phoenix"
            mascot: "Suns"
            conference: "Western"
            division: "Pacific"
            logoHref: "/public/img/nba/teams/suns.gif"
        -
            city: "Sacramento"
            mascot: "Kings"
            conference: "Western"
            division: "Pacific"
            logoHref: "/public/img/nba/teams/kings.gif"
# ==========
# MLB Config
# ==========
mlb:
    logoHref: "/public/img/mlb/mlb-logo.png"
    teams:
        # ==== AMERICAN LEAGUE ====
        # AL East
        -
            city: "Baltimore"
            mascot: "Orioles"
            conference: "American League"
            division: "AL East"
            logoHref: "/public/img/mlb/teams/bal.png"
            teamId: 110
        -
            city: "Boston"
            mascot: "Red Socks"
            conference: "American League"
            division: "AL East"
            logoHref: "/public/img/mlb/teams/bos.png"
            teamId: 111
        -
            city: "New York"
            mascot: "Yankees"
            conference: "American League"
            division: "AL East"
            logoHref: "/public/img/mlb/teams/nyy.png"
            teamId: 147
        -
            city: "Tampa Bay"
            mascot: "Rays"
            conference: "American League"
            division: "AL East"
            logoHref: "/public/img/mlb/teams/tb.png"
            teamId: 139
        -
            city: "Toronto"
            mascot: "Blue Jays"
            conference: "American League"
            division: "AL East"
            logoHref: "/public/img/mlb/teams/tor.png"
            teamId: 141
        # AL Central
        -
            city: "Chicago"
            mascot: "White Sox"
            conference: "American League"
            division: "AL Central"
            logoHref: "/public/img/mlb/teams/cws.png"
            teamId: 145
        -
            city: "Cleveland"
            mascot: "Indians"
            conference: "American League"
            division: "AL Central"
            logoHref: "/public/img/mlb/teams/cle.png"
            teamId: 114
        -
            city: "Detroit"
            mascot: "Tigers"
            conference: "American League"
            division: "AL Central"
            logoHref: "/public/img/mlb/teams/det.png"
            teamId: 116
        -
            city: "Kansas City"
            mascot: "Royals"
            conference: "American League"
            division: "AL Central"
            logoHref: "/public/img/mlb/teams/kc.png"
            teamId: 118
        -
            city: "Minnesota"
            mascot: "Twins"
            conference: "American League"
            division: "AL Central"
            logoHref: "/public/img/mlb/teams/min.png"
            teamId: 142
        # AL West
        -
            city: "Houston"
            mascot: "Astros"
            conference: "American League"
            division: "AL West"
            logoHref: "/public/img/mlb/teams/hou.png"
            teamId: 117
        -
            city: "Los Angeles"
            mascot: "Angels"
            conference: "American League"
            division: "AL West"
            logoHref: "/public/img/mlb/teams/ana.png"
            teamId: 108
        -
            city: "Oakland"
            mascot: "Athletics"
            conference: "American League"
            division: "AL West"
            logoHref: "/public/img/mlb/teams/oak.png"
            teamId: 133
        -
            city: "Seattle"
            mascot: "Mariners"
            conference: "American League"
            division: "AL West"
            logoHref: "/public/img/mlb/teams/sea.png"
            teamId: 136
        -
            city: "Texas"
            mascot: "Rangers"
            conference: "American League"
            division: "AL West"
            logoHref: "/public/img/mlb/teams/tex.png"
            teamId: 140
        # ==== NATIONAL LEAGUE ====
        # NL East
        -
            city: "Atlanta"
            mascot: "Braves"
            conference: "National League"
            division: "NL East"
            logoHref: "/public/img/mlb/teams/atl.png"
            teamId: 144
        -
            city: "Miami"
            mascot: "Marlins"
            conference: "National League"
            division: "NL East"
            logoHref: "/public/img/mlb/teams/mia.png"
            teamId: 146
        -
            city: "New York"
            mascot: "Mets"
            conference: "National League"
            division: "NL East"
            logoHref: "/public/img/mlb/teams/nym.png"
            teamId: 121
        -
            city: "Philadelphia"
            mascot: "Phillies"
            conference: "National League"
            division: "NL East"
            logoHref: "/public/img/mlb/teams/phi.png"
            teamId: 143
        -
            city: "Washington"
            mascot: "Nationals"
            conference: "National League"
            division: "NL East"
            logoHref: "/public/img/mlb/teams/was.png"
            teamId: 120
        # NL Central
        -
            city: "Chicago"
            mascot: "Cubs"
            conference: "National League"
            division: "NL Central"
            logoHref: "/public/img/mlb/teams/chc.png"
            teamId: 112
        -
            city: "Cincinnati"
            mascot: "Reds"
            conference: "National League"
            division: "NL Central"
            logoHref: "/public/img/mlb/teams/cin.png"
            teamId: 113
        -
            city: "Milwaukee"
            mascot: "Brewers"
            conference: "National League"
            division: "NL Central"
            logoHref: "/public/img/mlb/teams/mil.png"
            teamId: 158
        -
            city: "Pittsburgh"
            mascot: "Pirates"
            conference: "National League"
            division: "NL Central"
            logoHref: "/public/img/mlb/teams/pit.png"
            teamId: 134
        -
            city: "St. Louis"
            mascot: "Cardinals"
            conference: "National League"
            division: "NL Central"
            logoHref: "/public/img/mlb/teams/stl.png"
            teamId: 138
        # NL West
        -
            city: "Arizona"
            mascot: "Diamondbacks"
            conference: "National League"
            division: "NL West"
            logoHref: "/public/img/mlb/teams/ari.png"
            teamId: 109
        -
            city: "Colorado"
            mascot: "Rockies"
            conference: "National League"
            division: "NL West"
            logoHref: "/public/img/mlb/teams/col.png"
            teamId: 115
        -
            city: "Los Angeles"
            mascot: "Dodgers"
            conference: "National League"
            division: "NL West"
            logoHref: "/public/img/mlb/teams/la.png"
            teamId: 119
        -
            city: "San Diego"
            mascot: "Padres"
            conference: "National League"
            division: "NL West"
            logoHref: "/public/img/mlb/teams/sd.png"
            teamId: 135
        -
            city: "San Francisco"
            mascot: "Giants"
            conference: "National League"
            division: "NL West"
            logoHref: "/public/img/mlb/teams/sf.png"
            teamId: 137
